PREFIX base: <https://fireforce6.github.io/sierra/base#>
PREFIX capability: <https://fireforce6.github.io/sierra/capability#>

SELECT DISTINCT ?cap ?cap_desc ?req
WHERE {
    ?cap a capability:Capability ;
         base:description ?cap_desc .
    
    OPTIONAL {
        ?cap capability:isDerivedFrom ?req .
    }
}
ORDER BY ?cap
