PREFIX base: <https://fireforce6.github.io/sierra/base#>
PREFIX requirement: <https://fireforce6.github.io/sierra/requirement#>

SELECT DISTINCT ?stakeholder ?stakeholder_desc
WHERE {
    ?stakeholder a requirement:Stakeholder ;
                 base:description ?stakeholder_desc .
}
ORDER BY ?stakeholder
